api_platform:
    title: 'Symfony REST API'
    description: 'A Symfony API REST to manage some contacts.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
